<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Testimonial_play</name>
   <tag></tag>
   <elementGuidId>601096f0-4f7d-4b7b-8af1-83f324154a42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='LcjN1PTsPy8']/div)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.item__third > #LcjN1PTsPy8 > div.play</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd06ec8d-05c6-45f1-b234-cd921748d501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>play</value>
      <webElementGuid>458a8826-033f-4538-8007-e9a205f38444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselPeekEdges-Testimonial-testimonial&quot;)/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;carousel-item active&quot;]/div[@class=&quot;item__third&quot;]/div[@id=&quot;LcjN1PTsPy8&quot;]/div[@class=&quot;play&quot;]</value>
      <webElementGuid>736a402d-881c-4595-b788-be1e63b8f481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='LcjN1PTsPy8']/div)[2]</value>
      <webElementGuid>d634c365-6a9c-47e8-801c-60172d178c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[2]/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>2e01a379-ba7b-4625-b0ac-198cb5601961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
