<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Testimonial_carousel-control-prev-icon</name>
   <tag></tag>
   <elementGuidId>4b3bac0a-0ad1-4a66-b440-66f2ef79b117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselPeekEdges-Testimonial-testimonial']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.carousel-control-prev-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c85d1cf-127c-4752-aab6-6379ea20828a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-prev-icon</value>
      <webElementGuid>e0443ef7-8115-4246-9b8d-d3465d9178cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c8462ed-ed1a-40ff-841f-b7448957e543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselPeekEdges-Testimonial-testimonial&quot;)/a[@class=&quot;carousel-control-prev&quot;]/span[@class=&quot;carousel-control-prev-icon&quot;]</value>
      <webElementGuid>820d521b-72f6-4007-a7ba-d5a23c9c1ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselPeekEdges-Testimonial-testimonial']/a/span</value>
      <webElementGuid>13a39622-cabf-4616-9fba-cbbc8889b19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/span</value>
      <webElementGuid>4464523a-00fc-4ca2-b74b-28ee29b85599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
