<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tentang Kami</name>
   <tag></tag>
   <elementGuidId>1219905d-5cd0-421a-9b03-fce4db40ac2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='index-page']/body/div/div[2]/div[4]/div[12]/div/div[3]/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Tentang Kami&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09d15fa2-fa78-40ee-8c0f-61632dce34eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.pegipegi.com/team/index.html</value>
      <webElementGuid>67593004-3ae2-4adc-a33e-3048a4660263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tentang Kami</value>
      <webElementGuid>74e150c4-bd54-48cd-9dfd-58f82784b704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentang Kami</value>
      <webElementGuid>2892f1dc-6360-43c4-8fa3-105b9ac0df2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-page&quot;)/body[1]/div[@class=&quot;outer-wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;homeMainWidget&quot;]/div[@class=&quot;footer-wrapper&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;footer-middle-content&quot;]/div[@class=&quot;middle-content-first&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>c0ffb7c4-f9e7-4f14-bad2-1d36a941eb5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='index-page']/body/div/div[2]/div[4]/div[12]/div/div[3]/div/ul/li/a</value>
      <webElementGuid>440bee7f-d4cb-4bb0-b464-9ce0fc26d9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tentang Kami')]</value>
      <webElementGuid>392caa74-da43-4a7c-a0c7-e0cc905d722e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Pegipegi'])[1]/following::a[1]</value>
      <webElementGuid>62e433f9-440f-4f23-bbce-43f73dc67ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMO EKSKLUSIF dari Pegipegi!'])[1]/following::a[3]</value>
      <webElementGuid>e392a420-761c-4579-be3a-0690a354e679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[1]/preceding::a[1]</value>
      <webElementGuid>d0f1183f-37ec-4f80-9b34-f9e0118838b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[2]</value>
      <webElementGuid>fac195f4-50ae-40da-b5ad-f2eab618d37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tentang Kami']/parent::*</value>
      <webElementGuid>0ee41cb8-9a23-4a3d-80ac-c8f472cf8ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '//www.pegipegi.com/team/index.html')]</value>
      <webElementGuid>a99bd5e8-75a0-4e3a-889c-f54f8b0b9e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a</value>
      <webElementGuid>ef7c1ae0-9671-49e0-91fd-0edf57c0bfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.pegipegi.com/team/index.html' and @title = 'Tentang Kami' and (text() = 'Tentang Kami' or . = 'Tentang Kami')]</value>
      <webElementGuid>53ac3d04-0b9f-4c70-8ee4-95bfc4256d66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
