<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lebih Detail</name>
   <tag></tag>
   <elementGuidId>0f41c142-3818-48e7-9d3c-84b25c8d304e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='index-page']/body/div/div[2]/div[4]/div[6]/div/ul/li/a/div/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.formButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c5a269f-ee5a-4d59-9b33-6e6da7723e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formButton</value>
      <webElementGuid>559baaed-608e-4cf1-b51d-5577fb1946a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lebih Detail</value>
      <webElementGuid>38a8901d-a143-4259-bcfe-c787b585c777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;index-page&quot;)/body[1]/div[@class=&quot;outer-wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;homeMainWidget&quot;]/div[@class=&quot;widget promoTerkini&quot;]/div[@class=&quot;content&quot;]/ul[@class=&quot;listPromo-wrap&quot;]/li[1]/a[1]/div[@class=&quot;listPromo&quot;]/span[@class=&quot;formButton&quot;]</value>
      <webElementGuid>2236ecbe-f438-43d7-a56c-0fac49e8a74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='index-page']/body/div/div[2]/div[4]/div[6]/div/ul/li/a/div/span[3]</value>
      <webElementGuid>e45a3ed5-dd13-45a2-8829-0cadc5e0ff3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode promo: s.d. 29 Mei 2022'])[1]/following::span[1]</value>
      <webElementGuid>08923346-a73e-49e5-99a3-b48f792379c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon Hotel'])[1]/following::span[2]</value>
      <webElementGuid>811ab895-5336-440b-9871-ac1f90ffc0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon Tiket Pesawat'])[1]/preceding::span[2]</value>
      <webElementGuid>e665f378-824a-4ed9-abea-1d9afbbe8af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode promo: s.d. 29 Mei 2022'])[2]/preceding::span[2]</value>
      <webElementGuid>a449f19a-5f8d-45a6-8e5c-604e9e519026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lebih Detail']/parent::*</value>
      <webElementGuid>253324a8-5980-4937-8c2a-01e1fa36f348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span[3]</value>
      <webElementGuid>282d325b-e2a7-40c5-9c51-883fa065cf01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lebih Detail' or . = 'Lebih Detail')]</value>
      <webElementGuid>3e632175-da67-4b46-ab69-c8b07a1c3ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
