<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Platform_inside-left</name>
   <tag></tag>
   <elementGuidId>366079bd-7cf1-46a6-9985-a06e537f55f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='platform']/div/div/div/a[2]/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9dfc6436-42a8-4d3b-b119-2762eb1b0ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sites/default/files/2021-02/logo%20tAdex_0.png</value>
      <webElementGuid>7e0b89d7-6f1e-4919-90d4-6b97fbd8b1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TAdeX</value>
      <webElementGuid>a5ad859e-72bf-4509-a92d-9afcf462c24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inside-left</value>
      <webElementGuid>391f90ca-04e3-4abd-b0a7-ae9647ac6feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>4086165104</value>
      <webElementGuid>adbf975e-d9fc-4d04-88e9-867962a83daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>22f35793-1181-44da-b3f4-29b51f868128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container-fluid p-0 desktop-display&quot;]/div[@id=&quot;window&quot;]/nav[@class=&quot;navbar navbar-expand-md navbar-custom&quot;]/div[@id=&quot;navbarSupportedContent&quot;]/ul[@class=&quot;clearfix navbar-nav d-flex h-100&quot;]/li[@id=&quot;platform&quot;]/div[@class=&quot;dropdown-menu rounded-0 bg-light w-100 border-0 m-0 p-0 shadow-sm show&quot;]/div[@class=&quot;container-fluid d-block&quot;]/div[@class=&quot;row&quot;]/a[@class=&quot;nav col-6 p-0&quot;]/div[@class=&quot;posititon-relative img-left&quot;]/div[@class=&quot;text-inside left-wrap&quot;]/img[@class=&quot;inside-left&quot;]</value>
      <webElementGuid>5147a484-8091-42f2-a882-24f0f64735cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='platform']/div/div/div/a[2]/div/div[2]/img</value>
      <webElementGuid>7d26301f-353b-473d-9d6f-cb8b561b7969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='TAdeX']</value>
      <webElementGuid>6f81a54a-674a-42fb-b815-25d777d42bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div[2]/img</value>
      <webElementGuid>33216a2b-c614-40d6-8cf2-6c3a66865faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/sites/default/files/2021-02/logo%20tAdex_0.png' and @alt = 'TAdeX']</value>
      <webElementGuid>d1b5b3f1-2525-4194-a88b-5403131fcae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
