<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_promo</name>
   <tag></tag>
   <elementGuidId>a6c9602f-bc65-414b-9e17-2f1b24fdeb72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='facet-custom']/div/div/ul/li[4]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9be1dbea-c647-4aa2-b820-57b7bc2acc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>facet-item__value</value>
      <webElementGuid>777b8563-5c2f-4385-b197-1c0d78531bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>promo</value>
      <webElementGuid>1ffb307b-e486-46d1-8699-23ea9635f528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facet-custom&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1&quot;]/ul[@class=&quot;facet-inactive js-facets-links nav nav-tabs item-list__links&quot;]/li[@class=&quot;facet-item&quot;]/a[1]/span[@class=&quot;facet-item__value&quot;]</value>
      <webElementGuid>548018a3-cae1-4aeb-909c-6a007e9252f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='facet-custom']/div/div/ul/li[4]/a/span</value>
      <webElementGuid>1a470636-ea13-49e7-85d4-0614721afa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='berita'])[5]/following::span[1]</value>
      <webElementGuid>049aa944-e683-4dac-a282-38a0970cafa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='event'])[1]/following::span[2]</value>
      <webElementGuid>c985c6b0-6c37-4f89-a55c-97ad3a5e5de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/preceding::span[1]</value>
      <webElementGuid>5a376e18-c2a8-4aaa-8244-7be508368e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAdeX'])[2]/preceding::span[1]</value>
      <webElementGuid>867f0e05-21d5-4c6d-a54d-11b913eaf5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='promo']/parent::*</value>
      <webElementGuid>9656094c-3cc7-467b-b7cc-324ec46d714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>7c51abb4-5fbf-48ce-b71e-5170c46c5bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'promo' or . = 'promo')]</value>
      <webElementGuid>984adcae-bcf1-4e17-9ed8-c6591c100eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
