<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_berita</name>
   <tag></tag>
   <elementGuidId>e9ebd60d-ad50-4031-a5c3-610b122bfe39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='facet-custom']/div/div/ul/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c3bae8d-83eb-4900-b49a-d7590707741a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>facet-item__value</value>
      <webElementGuid>2a7c7a8a-97b9-4d5f-9a38-aec10fb0a6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>berita</value>
      <webElementGuid>a24c83aa-bb52-4f47-a4bd-2851dd0cd8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facet-custom&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1&quot;]/ul[@class=&quot;facet-inactive js-facets-links nav nav-tabs item-list__links&quot;]/li[@class=&quot;facet-item&quot;]/a[1]/span[@class=&quot;facet-item__value&quot;]</value>
      <webElementGuid>e58f9ba2-5052-40b2-a03c-bff199a0dff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='facet-custom']/div/div/ul/li[3]/a/span</value>
      <webElementGuid>bef20d1a-6809-4d39-8683-8af8edad751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='event'])[13]/following::span[1]</value>
      <webElementGuid>79097372-2483-4b18-bb6f-f15115b492ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[2]</value>
      <webElementGuid>7033d408-0602-43fd-92d8-ed345446925c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='promo'])[5]/preceding::span[1]</value>
      <webElementGuid>d6ade4c1-c176-4335-b669-5ec5b471b18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/preceding::span[2]</value>
      <webElementGuid>af899db4-a6c3-458a-b567-77d27dcb18fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='berita']/parent::*</value>
      <webElementGuid>8db35355-0872-4b44-8d8f-d52cdf204d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a/span</value>
      <webElementGuid>af15d186-ce54-45bc-a92d-14fb715820b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'berita' or . = 'berita')]</value>
      <webElementGuid>626636d4-1713-4036-b73f-efbde4de0735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
