<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Solusi_arrow-down hide-toggle</name>
   <tag></tag>
   <elementGuidId>cc88cd52-c4c9-4092-afca-757075293504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='navbarDropdown']/em)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.arrow-down.hide-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>3e9475b6-de85-4e57-baa6-408d9c6d99f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow-down hide-toggle</value>
      <webElementGuid>2acbd787-c0c3-42fe-89cd-2706cf0c2e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container-fluid p-0 desktop-display&quot;]/div[@id=&quot;window&quot;]/nav[@class=&quot;navbar navbar-expand-md navbar-custom&quot;]/div[@id=&quot;navbarSupportedContent&quot;]/ul[@class=&quot;clearfix navbar-nav d-flex align-items-center h-100&quot;]/li[@id=&quot;solusi&quot;]/a[@id=&quot;navbarDropdown&quot;]/em[@class=&quot;arrow-down hide-toggle&quot;]</value>
      <webElementGuid>659f074d-58fa-4e48-aa3c-90914b93681a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='navbarDropdown']/em)[2]</value>
      <webElementGuid>7b5bd034-b63b-4aae-8572-e65c230eabf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]/em</value>
      <webElementGuid>e9dd109c-a2ec-4253-b822-7dfa8e580260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
