<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Platform_img-responsive</name>
   <tag></tag>
   <elementGuidId>5a4c9bbf-1662-4027-8172-03ab99f0169e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-digiads-branding']/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3647a5d3-c534-4683-9f09-516e1c9806fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sites/default/files/logo-png.png</value>
      <webElementGuid>e229c854-9eb1-49da-a3f2-9007d0386e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>9db63f7f-251f-4292-aa8c-25cee5014caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>66b53cab-cc93-4e80-9d11-b9655c9103be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>1575300959</value>
      <webElementGuid>421b52c9-473e-4799-91c3-345a212a37fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>8ff37b8c-b29c-4844-9407-5c7ac0bb2b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container-fluid p-0 desktop-display&quot;]/div[@id=&quot;window&quot;]/nav[@class=&quot;navbar navbar-expand-md navbar-custom&quot;]/div[@class=&quot;clearfix region region-header&quot;]/div[@id=&quot;block-digiads-branding&quot;]/a[@class=&quot;logo pl-5&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>6e311dfc-82da-4c50-bc13-319cd6d1cc64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-digiads-branding']/a/img</value>
      <webElementGuid>80f264ed-ad5a-4919-8111-93e1ea0fc173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Home']</value>
      <webElementGuid>43ba872c-6d07-4a8b-a3c4-04e875181d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1cef9045-9cb9-4556-9aeb-00d6053fe6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/sites/default/files/logo-png.png' and @alt = 'Home']</value>
      <webElementGuid>b71487ca-c2bc-4450-9ab9-c5cdada3e387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
