<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pelajari Produk</name>
   <tag></tag>
   <elementGuidId>5a1b99bb-fcc4-455d-a876-c91c72657b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='marketing-A_HoujV1Dz99LUB7BL96']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.w-50.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f46f6d3-767e-4e63-bb3b-baf9d7b65582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>00e2c958-2767-4554-889c-49f504edab2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger w-50 pull-right</value>
      <webElementGuid>8316ef91-5e25-4ac2-9d37-d2a843fdd568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value> /solution/marketing-intelligence </value>
      <webElementGuid>952c9d8c-8612-40c5-9579-2138ef6b2b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pelajari Produk</value>
      <webElementGuid>fcb96606-c772-47c8-9a08-734a53b261db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketing-A_HoujV1Dz99LUB7BL96&quot;)/div[@class=&quot;col-lg-5 mt-4 aos-init aos-animate&quot;]/div[1]/a[@class=&quot;btn btn-danger w-50 pull-right&quot;]</value>
      <webElementGuid>7cc5cc65-1bd5-4c24-81f8-e757b4247e44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='marketing-A_HoujV1Dz99LUB7BL96']/div/div/a</value>
      <webElementGuid>3c66eb95-bf30-42b9-a83c-59c8b27bd94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pelajari Produk')])[5]</value>
      <webElementGuid>4e4b16a1-b39a-49dd-b5ff-0c29ee7454b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='insight dan solusi'])[2]/following::a[1]</value>
      <webElementGuid>d1b1044f-1ba0-4a84-9a65-dedf81a317de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing Intelligence'])[3]/following::a[1]</value>
      <webElementGuid>a41c7941-984f-43b8-bf02-6c5333f51b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Advertising'])[4]/preceding::a[1]</value>
      <webElementGuid>ee7d042f-6d2e-4db2-af27-1d18684b4bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='luas dan tepat sasaran'])[2]/preceding::a[1]</value>
      <webElementGuid>cdd9870b-721b-4e37-90b3-47822cd09e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, ' /solution/marketing-intelligence ')]</value>
      <webElementGuid>b4b13119-2224-409e-984c-a3d63d89499b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/a</value>
      <webElementGuid>2e482b3b-f9c1-420b-81fc-3a06abf54d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = ' /solution/marketing-intelligence ' and (text() = ' Pelajari Produk' or . = ' Pelajari Produk')]</value>
      <webElementGuid>98280030-5c85-4576-85de-132e9ee00d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
