<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Platform_arrow-down</name>
   <tag></tag>
   <elementGuidId>f5060966-f4c3-41fe-a716-3a1cb8a32467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.arrow-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbarDropdown']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>3f8ce0d8-5ebb-488e-9d75-1de54fba70f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow-down</value>
      <webElementGuid>ff59b320-afa7-4815-b379-b2de6d992543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container-fluid p-0 desktop-display&quot;]/div[@id=&quot;window&quot;]/nav[@class=&quot;navbar navbar-expand-md navbar-custom&quot;]/div[@id=&quot;navbarSupportedContent&quot;]/ul[@class=&quot;clearfix navbar-nav d-flex align-items-center h-100&quot;]/li[@id=&quot;platform&quot;]/a[@id=&quot;navbarDropdown&quot;]/em[@class=&quot;arrow-down&quot;]</value>
      <webElementGuid>276e9e9c-ec0e-43f1-a45d-13b8ed059a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navbarDropdown']/em</value>
      <webElementGuid>85009aea-651c-4f26-948f-2adaeb90d3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>59dcd3f7-958c-4ed4-9c05-0c152ab5acda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
