<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Solusi_arrow-down</name>
   <tag></tag>
   <elementGuidId>7c59a35d-bba5-414f-82fd-108afc00460a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='navbarDropdown']/em)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#solusi > #navbarDropdown > em.arrow-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>6784c4de-84eb-42a9-b4e3-2bbec2a83e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow-down</value>
      <webElementGuid>9b20055b-7f46-4fd3-b6f7-f9408e8a92c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container-fluid p-0 desktop-display&quot;]/div[@id=&quot;window&quot;]/nav[@class=&quot;navbar navbar-expand-md navbar-custom&quot;]/div[@id=&quot;navbarSupportedContent&quot;]/ul[@class=&quot;clearfix navbar-nav d-flex align-items-center h-100&quot;]/li[@id=&quot;solusi&quot;]/a[@id=&quot;navbarDropdown&quot;]/em[@class=&quot;arrow-down&quot;]</value>
      <webElementGuid>ae44be76-7f4a-4284-9e4a-de821f87d979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='navbarDropdown']/em)[2]</value>
      <webElementGuid>78335c66-70cf-41e2-b326-5fc39453b1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]/em</value>
      <webElementGuid>0e7f8615-8441-4d86-9c0b-d1339703cce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
