<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Beriklan Sekarang_fa fa-angle-left (1)</name>
   <tag></tag>
   <elementGuidId>9b56bf67-74ac-4ea2-9bfe-c0fa66bf76a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-digiads-content']/div/article/div/div/div/div[2]/div[2]/div/div/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8be5564f-ba5b-485c-a5a8-6722cee8a1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-left</value>
      <webElementGuid>b5f732cd-6563-469d-9f00-c30b807dcbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fd473e5-2156-4339-be13-061f513f5e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-digiads-content&quot;)/div[@class=&quot;content&quot;]/article[@class=&quot;node node--type-page node--view-mode-full clearfix&quot;]/div[@class=&quot;node__content clearfix&quot;]/div[1]/div[1]/div[@class=&quot;container-fluid  p-0 desktop-display&quot;]/div[@class=&quot;owl-theme&quot;]/div[@class=&quot;owl-controls&quot;]/div[@class=&quot;custom-nav owl-nav&quot;]/button[@class=&quot;owl-prev&quot;]/i[@class=&quot;fa fa-angle-left&quot;]</value>
      <webElementGuid>ef66bbcc-433e-4a3f-9975-80ef0046f34b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-digiads-content']/div/article/div/div/div/div[2]/div[2]/div/div/button[2]/i</value>
      <webElementGuid>0913aa8a-276f-48de-b163-0970ba533715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>d3456e7f-8a65-464e-9e1c-e52e9adbfb29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
