<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IndustryApparelPersonal AccessoriesA_615908</name>
   <tag></tag>
   <elementGuidId>17af67bd-78af-453d-964e-1b677b3c19f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-industri']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-industri</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>32bb0093-26b6-4936-b6a8-bae66e95f193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-industri</value>
      <webElementGuid>af9df306-cde8-479e-9a9f-e2e1689984d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-industri</value>
      <webElementGuid>869486d8-5f63-4316-a923-9c1a113a9c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>industri</value>
      <webElementGuid>fb360f45-d929-4e78-b09a-0f546170707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>3c38aa8d-013c-40d3-b17a-7cda2e25731e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>enableButton()</value>
      <webElementGuid>c3335fc4-bd65-4a3d-86b6-668f9e534bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IndustryApparel/Personal AccessoriesAutomotive &amp; AccesoriesBankingBevaragesCigaretteEducationFinancial non BankingFoodGovernment &amp; Public ServiceHealthcare &amp; PharmaceuticalHospitality, Recreation &amp; EntertainmentHousehold Equipment &amp; ApplianceIndustrial ProductLifestyleMarket PlaceMedia &amp; PromotionOnline TransportationOnline Travel AgencyRetailService PropertyTransportation</value>
      <webElementGuid>8d12cc48-63fb-4fd3-a94c-a01ea9e13f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layanan-iklan&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;wrapper-text col-sm-12 mt-5 mb-5&quot;]/form[@id=&quot;views-exposed-form-filtering-layanan-iklan-filtering-layanan-iklan&quot;]/div[@class=&quot;dropdown col-md-12 col-lg-4 col-12&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;styled-select dropdown-select&quot;]/select[@id=&quot;edit-industri&quot;]</value>
      <webElementGuid>e07fb8f5-8af4-41dc-997f-f03e8c50d368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-industri']</value>
      <webElementGuid>746dddec-eb1b-4728-acbc-7a0f653a1cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='views-exposed-form-filtering-layanan-iklan-filtering-layanan-iklan']/div/div/div/select</value>
      <webElementGuid>984723f7-a46f-4259-ac46-cca1b04b01f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Layanan Iklan'])[1]/following::select[1]</value>
      <webElementGuid>b05516dd-3e10-4fa9-ad75-a322b4ca4022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hari'])[2]/following::select[1]</value>
      <webElementGuid>571b62d3-174b-4355-8c2d-51ab5504b24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Layanan Iklan'])[2]/preceding::select[2]</value>
      <webElementGuid>e7b09999-13e2-4ce2-9a85-88bd806f5c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing Intelligence'])[2]/preceding::select[4]</value>
      <webElementGuid>4fcc10a3-feb5-4654-bf80-e116da3b285c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/select</value>
      <webElementGuid>38bcc69f-1096-479a-a66c-80ddba54a271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edit-industri' and @name = 'industri' and (text() = 'IndustryApparel/Personal AccessoriesAutomotive &amp; AccesoriesBankingBevaragesCigaretteEducationFinancial non BankingFoodGovernment &amp; Public ServiceHealthcare &amp; PharmaceuticalHospitality, Recreation &amp; EntertainmentHousehold Equipment &amp; ApplianceIndustrial ProductLifestyleMarket PlaceMedia &amp; PromotionOnline TransportationOnline Travel AgencyRetailService PropertyTransportation' or . = 'IndustryApparel/Personal AccessoriesAutomotive &amp; AccesoriesBankingBevaragesCigaretteEducationFinancial non BankingFoodGovernment &amp; Public ServiceHealthcare &amp; PharmaceuticalHospitality, Recreation &amp; EntertainmentHousehold Equipment &amp; ApplianceIndustrial ProductLifestyleMarket PlaceMedia &amp; PromotionOnline TransportationOnline Travel AgencyRetailService PropertyTransportation')]</value>
      <webElementGuid>b4720282-1de3-4bfd-9bf1-89725e42737a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
