<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GoalsApp InstallsAwarenessConversion_43869a</name>
   <tag></tag>
   <elementGuidId>005e7e6d-9209-469a-8a10-2a6d46758ae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit-goal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-goal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd00ff24-76c9-45cf-96f8-515f7d9bc4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-goal</value>
      <webElementGuid>2e3883c7-16e8-41bb-90bb-13fcb13dd0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-goal</value>
      <webElementGuid>96d0cc82-056a-4ac4-84e2-4d0eae64014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>goal</value>
      <webElementGuid>cc548b9d-2009-470d-b44b-98d095175ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>711f1524-3007-4283-a811-c0b726bd8435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>enableButton()</value>
      <webElementGuid>efe9870c-9147-491b-b6ee-ca5cd13c0931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GoalsApp InstallsAwarenessConversionEngagementInsight DataLead GenerationTraffic</value>
      <webElementGuid>f92041df-f789-4576-9dc9-f7b3eeeb4f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layanan-iklan&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;wrapper-text col-sm-12 mt-5 mb-5&quot;]/form[@id=&quot;views-exposed-form-filtering-layanan-iklan-filtering-layanan-iklan&quot;]/div[@class=&quot;dropdown col-md-12 col-lg-4 col-12&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;styled-select dropdown-select&quot;]/select[@id=&quot;edit-goal&quot;]</value>
      <webElementGuid>d95eeaf8-edc5-4ac2-9079-75dc800c8df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit-goal']</value>
      <webElementGuid>77287f18-3b61-4308-b463-eabc60fdcd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='views-exposed-form-filtering-layanan-iklan-filtering-layanan-iklan']/div[2]/div/div/select</value>
      <webElementGuid>29efcd52-8184-4264-840f-241a4de170f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Layanan Iklan'])[1]/following::select[2]</value>
      <webElementGuid>f42fe657-5d69-4039-bbe5-d05486cdded1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hari'])[2]/following::select[2]</value>
      <webElementGuid>f6a1e4d2-163c-4d9f-9837-885e3d240bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Layanan Iklan'])[2]/preceding::select[1]</value>
      <webElementGuid>854ad889-6cda-4f67-a721-d56e292ecaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing Intelligence'])[2]/preceding::select[3]</value>
      <webElementGuid>c9ceeca0-6cfb-4074-a15c-30e4a5f88fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>4ea51ef6-a1af-40cd-bebf-8c6f027f8c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edit-goal' and @name = 'goal' and (text() = 'GoalsApp InstallsAwarenessConversionEngagementInsight DataLead GenerationTraffic' or . = 'GoalsApp InstallsAwarenessConversionEngagementInsight DataLead GenerationTraffic')]</value>
      <webElementGuid>db56eec0-9573-421d-b301-591dd49c0c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
