<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Destinasi_widget-img-main wp-post-image</name>
   <tag></tag>
   <elementGuidId>1e40dbb0-dcbf-4d79-94a1-392555deae8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mvp_catlist_widget-2']/div/ul/li/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.widget-img-main.wp-post-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eece823a-0be8-4842-9e6d-f3b7c7dbc051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>204</value>
      <webElementGuid>d138c803-36fa-41ff-8d36-ab5c7900d27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>122</value>
      <webElementGuid>a6f15fdf-bf9b-44f2-80b4-bc04b19cfecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.pegipegi.com/travel/wp-content/uploads/2022/05/featured-image-11-300x180.jpg</value>
      <webElementGuid>70e239ef-3990-430d-a5c4-4ec804ecb605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-img-main wp-post-image</value>
      <webElementGuid>f41f1e36-8c30-4f5d-bbfe-76039d44623b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>gereja terindah di Asia</value>
      <webElementGuid>63db710d-bdbc-4c38-8ce2-b63f3696c6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>1b332b94-cab5-47a3-b182-70eac175c7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://www.pegipegi.com/travel/wp-content/uploads/2022/05/featured-image-11-300x180.jpg 300w, https://www.pegipegi.com/travel/wp-content/uploads/2022/05/featured-image-11-1000x600.jpg 1000w, https://www.pegipegi.com/travel/wp-content/uploads/2022/05/featured-image-11-450x270.jpg 450w</value>
      <webElementGuid>cea6e65a-5b85-4c9a-9eee-c6b5d4486b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>748ba8df-33cd-4276-bfa1-5ccbeadff59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mvp_catlist_widget-2&quot;)/div[@class=&quot;blog-widget-wrap left relative&quot;]/ul[@class=&quot;blog-widget-list noMargin left relative&quot;]/li[1]/a[1]/div[@class=&quot;blog-widget-img left relative&quot;]/img[@class=&quot;widget-img-main wp-post-image&quot;]</value>
      <webElementGuid>3d7cafe5-c2b0-4216-b66b-1845436c1bdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mvp_catlist_widget-2']/div/ul/li/a/div/img</value>
      <webElementGuid>98bae311-d52f-40e1-abcf-5d2a841c76d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='gereja terindah di Asia'])[3]</value>
      <webElementGuid>5c452cec-7b7c-4e87-88e1-c7dc5c274ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/div/img</value>
      <webElementGuid>836cae8b-d22d-4a14-af1c-29e7299d08de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.pegipegi.com/travel/wp-content/uploads/2022/05/featured-image-11-300x180.jpg' and @alt = 'gereja terindah di Asia']</value>
      <webElementGuid>6a17bb47-6d53-445e-836c-fb7ae4331f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
