<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Platform_inside-left</name>
   <tag></tag>
   <elementGuidId>a5cc407b-60d3-4e1c-8adb-eb7fd4729492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='platform']/div/div/div/a[2]/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>20dc23a3-3d4e-4d5d-8726-7a957bbc6294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TAdeX</value>
      <webElementGuid>7b5e572c-e124-4880-ab18-6171cdda2155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inside-left</value>
      <webElementGuid>f56eaee6-9795-4416-af7d-84289a564779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>4086165104</value>
      <webElementGuid>3aa84367-ac6c-43e4-ac01-93181dc28067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sites/default/files/2021-02/logo%20tAdex_0.png</value>
      <webElementGuid>c1abd695-08b0-41f1-805f-5823ba6a5957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);</value>
      <webElementGuid>3a13e6af-9c33-482b-905a-e84d21ea10d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container-fluid p-0 desktop-display&quot;]/div[@id=&quot;window&quot;]/nav[@class=&quot;navbar navbar-expand-md navbar-custom&quot;]/div[@id=&quot;navbarSupportedContent&quot;]/ul[@class=&quot;clearfix navbar-nav d-flex h-100&quot;]/li[@id=&quot;platform&quot;]/div[@class=&quot;dropdown-menu rounded-0 bg-light w-100 border-0 m-0 p-0 shadow-sm show&quot;]/div[@class=&quot;container-fluid d-block&quot;]/div[@class=&quot;row&quot;]/a[@class=&quot;nav col-6 p-0&quot;]/div[@class=&quot;posititon-relative img-left&quot;]/div[@class=&quot;text-inside left-wrap&quot;]/img[@class=&quot;inside-left&quot;]</value>
      <webElementGuid>c643f627-dc1f-4cbb-8682-0195c3737deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='platform']/div/div/div/a[2]/div/div[2]/img</value>
      <webElementGuid>2206c60c-607b-427b-b294-f4db1afcb8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='TAdeX']</value>
      <webElementGuid>2a3d6642-b740-423a-8195-2511b7db5896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div[2]/img</value>
      <webElementGuid>95816c11-9658-49b3-a979-9fe5e2f86d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'TAdeX' and @src = '/sites/default/files/2021-02/logo%20tAdex_0.png']</value>
      <webElementGuid>b40a5ee1-6fc5-4aea-a117-9324b3de00c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
